networks:
  - preprod
  - preview
  - mainnet

instances:
  qa:
    parentDomain: scdev.aws.iohkdev.io
    tag: latest
    repo: ghcr.io
    org: input-output-hk

namespace: marlowe-staging

releaseName: marlowe-runtime

databaseName: marlowe-runtime-database

databaseHost: dapps-marlowe-runtime-database.csguv6v6ban1.us-east-1.rds.amazonaws.com
