networks:
  - preprod
  - preview
  - mainnet
instances:
  qa:
    parentDomain: scdev.aws.iohkdev.io
    webTag: cba0918b
    tag: cba0918b
    repo: ghcr.io
    org: input-output-hk
    databaseHost: prod-marlowe-runtime-db-new.csguv6v6ban1.us-east-1.rds.amazonaws.com
  demo:
    parentDomain: demo.scdev.aws.iohkdev.io
    webTag: 0.0.5.1
    tag: 0.0.5
    repo: ghcr.io
    org: input-output-hk
    databaseHost: prod-marlowe-runtime-db-new.csguv6v6ban1.us-east-1.rds.amazonaws.com
  0_0_6:
    parentDomain: 0.0.6.scdev.aws.iohkdev.io
    webTag: 0.0.6
    tag: 0.0.6
    repo: ghcr.io
    org: input-output-hk
    databaseHost: prod-marlowe-runtime-db-new.csguv6v6ban1.us-east-1.rds.amazonaws.com
namespace: marlowe-staging
releaseName: marlowe-runtime
databaseName: marlowe-runtime-database
otelExporter:
  url: http://k8s-monitoring-grafana-agent.grafana-agent
  port: 4318
