networks:
  - preprod
  - preview
  - mainnet
instances:
  qa:
    parentDomain: scdev.aws.iohkdev.io
    webTag: 94821a97
    tag: 94821a97
    repo: ghcr.io
    org: input-output-hk
    cardanoNode: cardano-node-873
  demo:
    parentDomain: demo.scdev.aws.iohkdev.io
    webTag: 1.0.0
    tag: 1.0.0
    repo: ghcr.io
    org: input-output-hk
    cardanoNode: cardano-node
  0_0_6:
    parentDomain: 0.0.6.scdev.aws.iohkdev.io
    webTag: 0.0.6
    tag: 0.0.6
    repo: ghcr.io
    org: input-output-hk
    cardanoNode: cardano-node
namespace: marlowe-staging
releaseName: marlowe-runtime
databaseName: marlowe-runtime-database
otelExporter:
  url: http://k8s-monitoring-grafana-agent.grafana-agent
  port: 4318
